package:
  name: dataset-extent-to-features
  version: "0.1"

build:
  number: 0

source:
  git_rev: HEAD
  git_url: https://github.com/data-navigator/dataset-extent-to-features.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/data-navigator/dataset-extent-to-features
  license: Apache
